server {
    listen 80;
    server_name suivi-chauffeur.fr www.suivi-chauffeur.fr;
    return 301 https://;
}

server {
    listen 443 ssl;
    server_name suivi-chauffeur.fr www.suivi-chauffeur.fr;
    root /var/www/suivi-chauffeur;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/suivi-chauffeur.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/suivi-chauffeur.fr/privkey.pem;

    location / {
        try_files  / =404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|json|webp)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
